version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: coordinator_db
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator-service:
    image: dev4mz/test4mz:0.1.8
    container_name: coordinator_service
    ports:
      - 8000:8000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_DOCKER: coordinator_db
      NETWORK_ENDPOINT: wss://polkadot.api.onfinality.io/public-ws
    volumes:
      - /var/tmp/composeFiles:/var/tmp/composeFiles
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --network=testnet
      - --ws-endpoint=https://sqtn.api.onfinality.io/public
      - --postgres-host=postgres
      - --postgres-database=postgres
      - --postgres-port=5432
      - --port=8000
networks:
  default:
    external:
      name: cooridnator-service
