version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-coordinator:
    image: dev4mz/test4mz:0.1.1
    ports:
      - 8000:8000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    volumes:
      - /var/tmp/app/dist/compose-files:/app/dist/compose-files
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --network=testnet
      - --ws-endpoint=https://moonbeam-alpha.api.onfinality.io/public
      - --postgres-host=postgres
      - --postgres-database=postgres
      - --postgres-port=5432
      - --port=8000
networks:
  default:
    external:
      name: cooridnator-service
