version: "3"

services:
  {{nodeServiceName}}:
    image: onfinality/subql-node:{{nodeVersion}}
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: {{database}}
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app
      - --port={{servicePort}}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://{{nodeServiceName}}:{{servicePort}}/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 10

    {{queryName}}:
      image: onfinality/subql-query:{{queryVersion}}
      ports:
        - {{servicePort}}:{{servicePort}}
      depends_on:
        "{{nodeServiceName}}":
          condition: service_healthy
      restart: always
      environment:
        DB_USER: postgres
        DB_PASS: postgres
        DB_DATABASE: {{database}}
        DB_HOST: postgres
        DB_PORT: 5432
      command:
        - --name=app
        - --playground
        - --indexer=http://{{nodeServiceName}}:{{servicePort}}

networks:
  default:
    external:
      name: cooridnator-service
